# Generated by Django 3.0.5 on 2020-06-22 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Email Subject')),
                ('message', models.TextField(null=True, verbose_name='Email text')),
                ('date', models.DateField(default=datetime.date(2020, 6, 22))),
                ('time', models.TimeField(default=datetime.time(15, 15, 9, 78287))),
                ('check_send', models.BooleanField(db_index=True, default=False)),
                ('users', models.ManyToManyField(limit_choices_to={'Verified': True}, to='restaurant.UserProfile')),
            ],
        ),
    ]
