# Generated by Django 3.0.5 on 2020-06-22 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='time',
            field=models.TimeField(default=datetime.time(15, 15, 50, 867318)),
        ),
    ]
