# Generated by Django 3.0.5 on 2020-06-23 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200622_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
        migrations.AlterField(
            model_name='mailsender',
            name='time',
            field=models.TimeField(default=datetime.time(22, 26, 18, 317699)),
        ),
    ]
