# Generated by Django 3.0.5 on 2020-06-24 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200624_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='time',
            field=models.TimeField(default=datetime.time(17, 4, 27, 239103)),
        ),
    ]
