# Generated by Django 3.0.5 on 2020-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
