# Generated by Django 3.0.5 on 2020-05-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dish_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Events',
        ),
    ]
