# Generated by Django 3.0.5 on 2020-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20200519_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='name',
        ),
        migrations.AddField(
            model_name='cook',
            name='first_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cook',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
