# Generated by Django 3.0.5 on 2020-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200519_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='section',
        ),
    ]
