# Generated by Django 3.0.5 on 2020-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20200519_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
