# Generated by Django 3.0.5 on 2020-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20200519_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='section',
            field=models.CharField(choices=[('Холодные закуски', 'Холодные закуски'), ('Салаты', 'Салаты'), ('Горячие закуски', 'Горячие закуски'), ('Первые блюда', 'Первые блюда'), ('Основные блюда', 'Основные блюда'), ('Гарниры', 'Гарниры'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки')], max_length=30),
        ),
    ]
