# Generated by Django 3.0.5 on 2020-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20200519_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
