# Generated by Django 3.0.5 on 2020-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20200519_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='date',
            field=models.DateField(default=None, help_text='Начало работы в ресторане'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='first_name',
            field=models.CharField(help_text='Имя', max_length=20),
        ),
        migrations.AlterField(
            model_name='cook',
            name='last_name',
            field=models.CharField(help_text='Фамилия', max_length=20),
        ),
        migrations.AlterField(
            model_name='cook',
            name='position',
            field=models.CharField(help_text='Должность', max_length=40),
        ),
    ]
