# Generated by Django 3.0.5 on 2020-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20200519_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
