# Generated by Django 3.0.5 on 2020-05-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20200520_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя пользователя, оставившего отзыв', max_length=50)),
                ('text', models.TextField(help_text='Текст отзыва')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
