# Generated by Django 3.0.5 on 2020-05-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='date',
        ),
        migrations.AlterField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, upload_to='restaurant/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='restaurant/images/%Y/%m/%d'),
        ),
    ]
