# Generated by Django 3.0.5 on 2020-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20200521_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(default='', help_text='Должность', max_length=40),
        ),
    ]
