# Generated by Django 3.0.5 on 2020-05-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_contact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='date',
            field=models.DateTimeField(default=1, help_text='Начало работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(help_text='Номер телефона', max_length=30),
        ),
    ]
