# Generated by Django 3.0.5 on 2020-05-21 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_auto_20200521_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 19, 53, 42, 465649), help_text='Начало работы'),
        ),
    ]
