# Generated by Django 3.0.5 on 2020-05-21 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20200521_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 19, 58, 3, 435154), help_text='Начало работы'),
        ),
    ]
