# Generated by Django 3.0.5 on 2020-05-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_auto_20200521_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='date',
        ),
    ]
