# Generated by Django 3.0.5 on 2020-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200624_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, help_text='Заголовок', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(db_index=True, help_text='Название акции', max_length=50),
        ),
    ]
